[project]
name = "tabsmc"
version = "0.1.0"
description = "Tabular Sequential Monte Carlo implementation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax[cpu]>=0.4.0",
    "jaxlib>=0.4.0",
    "numpy>=1.24.0",
]
